/* eslint-disable linebreak-style */
/* eslint-disable no-undef */
import './AboutUs.css'
import '../img/TeamMember/BackMan.png'
import '../img/TeamMember/CEOman.png'
import '../img/TeamMember/CopyWriterWoman.png'
import '../img/TeamMember/DesignerMan.png'
import '../img/TeamMember/FrontMan.png'
import '../img/TeamMember/SMmWoman.png'
import '../img/social/faceBook.png'
import '../img/social/instagramm.png'
import '../img/social/vk.png'
import '../img/undraw_team.png'
import '../img/VectorBurger.png'
import '../img/Logo.png'
